const form = document.querySelector('#preferences');
const results = document.querySelector('#results');
const grid = document.querySelector('#recommendation-grid');
const modeBadge = document.querySelector('#mode-badge');
const summary = document.querySelector('#ai-summary');
const explanation = document.querySelector('#ai-explanation');
const reasonChips = document.querySelector('#reason-chips');
const feedbackNote = document.querySelector('#feedback-note');
const requestStatus = document.querySelector('#request-status');

const labels = {goal:{energy:'steady energy',protein:'more protein',light:'a light and balanced meal',comfort:'comfort food'},diet:{vegetarian:'vegetarian',vegan:'vegan',eggetarian:'eggetarian',any:'flexible'},cuisine:{any:'any cuisine','north-indian':'North Indian','south-indian':'South Indian',chinese:'Chinese',italian:'Italian',mexican:'Mexican',thai:'Thai',japanese:'Japanese',continental:'Continental'},flavor:{homestyle:'homestyle Indian',spicy:'bold and spicy',fresh:'fresh and light',familiar:'familiar comfort'},time:{15:'15 minutes',30:'30 minutes',60:'up to an hour'},budget:{low:'budget-friendly',mid:'moderate budget',high:'flexible budget'}};

const cuisinePhotos = {'north-indian':'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85','south-indian':'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=900&q=85',chinese:'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=900&q=85',italian:'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=85',mexican:'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=900&q=85',thai:'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=900&q=85',japanese:'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=900&q=85',continental:'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=900&q=85'};
const mealPhotos = {'Masala Moong Bowl':'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=85','Paneer Millet Wrap':'https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=900&q=85','Lemon Poha':'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=900&q=85','Rajma Rice Bowl':'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85','Chana Chaat':'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=900&q=85','Veg Hakka Noodles':'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=85','Margherita Pasta':'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=85','Masala Dosa':'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=900&q=85'};

function escapeHtml(value){return String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function photoForMeal(meal){return mealPhotos[meal.name] || cuisinePhotos[meal.cuisine] || cuisinePhotos['north-indian'];}
function cuisineForMeal(meal){if(meal.cuisine)return meal.cuisine;if(/dosa|poha/i.test(meal.name))return 'south-indian';if(/noodle|chilli paneer/i.test(meal.name))return 'chinese';if(/pasta|penne|margherita/i.test(meal.name))return 'italian';if(/taco|bean/i.test(meal.name))return 'mexican';if(/curry/i.test(meal.name))return 'thai';if(/sushi/i.test(meal.name))return 'japanese';return 'north-indian';}
function mealIllustration(name, index){
  const kind = /wrap/i.test(name) ? 'wrap' : /egg|bhurji/i.test(name) ? 'egg' : /poha/i.test(name) ? 'poha' : /chaat/i.test(name) ? 'chaat' : index % 2 ? 'bowl' : 'plate';
  const art = {bowl:'<path class="svg-bowl" d="M25 52h70c-4 25-15 34-35 34S29 77 25 52Z"/><ellipse class="svg-rim" cx="60" cy="52" rx="38" ry="12"/><circle class="svg-green" cx="43" cy="49" r="9"/><circle class="svg-red" cx="60" cy="47" r="8"/><circle class="svg-gold" cx="76" cy="51" r="9"/>',plate:'<ellipse class="svg-plate" cx="60" cy="64" rx="43" ry="12"/><path class="svg-bowl" d="M25 52h70c-4 22-15 31-35 31S29 74 25 52Z"/><circle class="svg-green" cx="42" cy="48" r="8"/><circle class="svg-red" cx="60" cy="45" r="9"/><circle class="svg-gold" cx="78" cy="49" r="8"/>',wrap:'<path class="svg-wrap" d="M31 29c14-7 42-7 58 0l-7 50c-15 8-29 8-44 0Z"/><path class="svg-line" d="M38 42c14 7 30 7 44 0M37 54c15 7 31 7 45 0M39 66c13 6 27 6 41 0"/><circle class="svg-red" cx="49" cy="35" r="6"/><circle class="svg-green" cx="67" cy="37" r="6"/>',egg:'<path class="svg-toast" d="M30 42c0-12 8-19 20-19h23c12 0 19 7 19 19v27c0 8-5 12-13 12H43c-8 0-13-4-13-12Z"/><path class="svg-egg" d="M47 55c-8-7-2-16 7-14 7-8 17-3 16 5 9 5 3 14-5 14-6 7-16 3-18-5Z"/><circle class="svg-gold" cx="57" cy="53" r="6"/>',poha:'<path class="svg-bowl" d="M25 49h70c-4 27-16 36-35 36S29 76 25 49Z"/><ellipse class="svg-rim" cx="60" cy="49" rx="37" ry="13"/><circle class="svg-gold" cx="43" cy="48" r="5"/><circle class="svg-gold" cx="55" cy="45" r="5"/><circle class="svg-green" cx="69" cy="49" r="5"/><circle class="svg-red" cx="79" cy="46" r="4"/>',chaat:'<path class="svg-bowl" d="M28 45h64c-4 28-15 39-32 39S32 73 28 45Z"/><ellipse class="svg-rim" cx="60" cy="45" rx="33" ry="12"/><circle class="svg-gold" cx="44" cy="43" r="7"/><circle class="svg-green" cx="58" cy="40" r="7"/><circle class="svg-red" cx="72" cy="44" r="7"/>'};
  return `<div class="meal-media"><img class="meal-photo" src="${escapeHtml(photoForMeal({name}))}" alt="Fresh food photo for ${escapeHtml(name)}" loading="lazy" onerror="this.classList.add('image-failed')"><div class="meal-illustration illustration-${kind}" role="img" aria-label="Illustration for ${escapeHtml(name)}"><svg viewBox="0 0 120 100" aria-hidden="true">${art[kind]}</svg><span class="illustration-spark">✦</span></div></div>`;
}
function render(data){
  const meals = data.recommendations || [];
  grid.innerHTML = meals.map((meal, index) => `<article class="meal-card">${mealIllustration(meal.name || 'Meal', index).replace('photoForMeal({name})', 'photoForMeal(meal)')}<div class="meal-cuisine">${escapeHtml(labels.cuisine[meal.cuisine] || meal.cuisine || 'Chef pick')}</div><h3>${escapeHtml(meal.name)}</h3><p>${escapeHtml(meal.description)}</p><div class="tag-row">${(meal.tags || []).map(tag => `<span class="tag">${escapeHtml(tag)}</span>`).join('')}</div></article>`).join('');
  const live = data.mode === 'real-ai'; modeBadge.textContent = live ? 'Live AI mode' : 'Local demo mode'; modeBadge.classList.toggle('live-mode', live);
  summary.textContent = data.summary || 'These choices fit the context you shared.'; explanation.textContent = data.explanation || ''; reasonChips.innerHTML = (data.reasons || []).map(reason => `<span class="reason-chip">${escapeHtml(reason)}</span>`).join(''); results.classList.remove('hidden'); results.scrollIntoView({behavior:'smooth', block:'start'});
}
function setRequestStatus(message, type=''){requestStatus.textContent=message;requestStatus.className=`request-status ${type}`;}
form.addEventListener('submit', async event => {event.preventDefault(); const button=form.querySelector('button'); const original=button.innerHTML; button.disabled=true; button.classList.add('is-loading'); button.innerHTML='<span class="button-spinner"></span> Thinking…'; setRequestStatus('SwaadAI is combining your preferences…','loading'); const preferences=Object.fromEntries(new FormData(form).entries()); try {const response=await fetch('/api/recommend',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(preferences)}); if(!response.ok) throw new Error('gateway unavailable'); const data=await response.json(); render(data); setRequestStatus(data.mode==='real-ai'?'Live AI recommendation ready.':'Showing a fast local demo recommendation.',data.mode==='real-ai'?'success':'demo');} catch(error){try{const fallbackResponse=await fetch('http://localhost:8000/recommend',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(preferences)});if(!fallbackResponse.ok)throw new Error('python unavailable');const fallback=await fallbackResponse.json();render(fallback);setRequestStatus('Using the local AI fallback while the gateway is unavailable.','demo');}catch(fallbackError){setRequestStatus('Recommendation service is offline. Start the Java and Python services, then try again.','error');modeBadge.textContent='Service offline';modeBadge.classList.remove('live-mode');}} finally{button.disabled=false;button.classList.remove('is-loading');button.innerHTML=original;}});
document.querySelectorAll('[data-feedback]').forEach(button=>button.addEventListener('click',()=>{feedbackNote.textContent=button.dataset.feedback==='yes'?'Thanks — this helps the recommender learn your taste.':'Got it — the next shortlist should adapt.';}));
